### ISSUE TITLE
Could somebody provide afFormGroup code example?

### ISSUE THREAD

**Issue by elnzv** [aldeed/meteor-autoform#1010]
Was trying to use afFormGroup method to show two fields in one line and failed.

Here is the code I am using for the schema:

```
  matching:
    type: [Object]

  "matching.$.frontend_prefix":
    label: 'Frontend Prefix'
    type: String

  "matching.$.backend_prefix":
    label: 'Backend Prefix'
    type: String
    regEx: /^[a-z0-9A-Z_]{3,15}$/

```
