### ISSUE TITLE
Mongo Error: Left Subfield only support object

### ISSUE THREAD

**Issue by aaronjudd** [aldeed/meteor-autoform#142]
This is not a critical bug by any means, but something that could probably be caught.

```
 Error: MongoError: LEFT_SUBFIELD only supports Object: settings not: 10 [409]
```

 And in the console:

```
details: undefined
error: 409
errorType: "Meteor.Error"
message: "MinimongoError: cannot use the part 'host' to traverse null [409]"
reason: "MinimongoError: cannot use the part 'host' to traverse null"
stack: "Error↵    at m.(anonymous function) (http://localhost:3000/packages/mongo-livedata.js?cf17a2975aa7445f0db2377c2af07e5efc240958:763:19)↵    at http://localhost:3000/packages/livedata.js?7f11e3eaafcbe13d80ab0fb510d25d9595e78de2:3818:25↵    at _.extend.withValue (http://localhost:3000/packages/meteor.js?148e9381d225ecad703f4b858769b636ff7a2537:794:17)↵    at _.extend.apply (http://localhost:3000/packages/livedata.js?7f11e3eaafcbe13d80ab0fb510d25d9595e78de2:3810:42)↵    at Meteor.Collection.(anonymous function) (http://localhost:3000/packages/mongo-livedata.js?cf17a2975aa7445f0db2377c2af07e5efc240958:531:26)↵    at Meteor.Collection.(anonymous function) (http://localhost:3000/packages/collection2.js?c5dee5a20521c7b3b076f05be20049f9ddc483a7:342:19)↵    at null.<anonymous> (http://localhost:3000/packages/collection-hooks.js?89f83e2f6326308895ccc2346424105bdcee726d:324:19)↵    at (anonymous function) [as update] (http://localhost:3000/packages/collection-hooks.js?89f83e2f6326308895ccc2346424105bdcee726d:103:21)↵    at Object.autoFormSubmitHandler (http://localhost:3000/packages/autoform.js?e9a4893232553129bdc3a9932ba2807e1e969130:2955:20)↵    at http://localhost:3000/packages/ui.js?b523ef986d3d39671bcb40319d0df8982acacfe8:410:30"
__proto__: tmp
```

Where the collection is schema is defined as such:

```
@MailgunConfigSchema = new SimpleSchema([
  PackageConfigSchema
  {
    settings:
      type: Object
      optional: true
    "settings.host":
      type: String
      label: "Host"
    "settings.port":
      type: Number
      label: "Port"
      allowedValues: [25, 587, 465, 475, 2525]
      defaultValue: 25
      optional: true
    "settings.username":
      type: String
      label: "Username"
    "settings.password":
      type: String
      label: "Password"
  }
])
```

The error occurs if the settings field has a null value of it already assigned.  So in this schema, the db already had _settings: null_ prior to running the update form.

The is probably repeatable by assigning any object field a null value then trying to update.
