### ISSUE TITLE
How to integrate with Meter.users collection

### ISSUE THREAD

**Issue by enaros** [aldeed/meteor-autoform#300]
Hi, I know you have a section where you explain that, but it isnt working form me
This is what I have so far

template.html

```
{{> quickForm collection=Users schema=schema doc=userDoc id="update-profile" type="update"}}
```

template.coffee

```
Template.dashboard.schema = -> Schema.contact
Template.dashboard.Users = -> Meteor.users
Template.dashboard.userDoc = -> Meteor.user()

Schema = {}
Schema.contact = new SimpleSchema
    firstName:
        type: String
        label: "Your name"
        max: 50
    lastName:
        type: String
        label: "Your last name"
        max: 50
    emailAddress:
        type: String
        regEx: SimpleSchema.RegEx.Email
        label: "E-mail address"
```

can you please tell me what I am doing wrong? :rocket:
