### ISSUE TITLE
array input fields get deleted on submit / focus bug

### ISSUE THREAD

**Issue by dcsan** [aldeed/meteor-autoform#397]
I have an autoform defined with:

```
  words:
    type: [String]
  cname:
    type: String

```

when the cursor is in the `cname` field and I hit "return", it will delete the first entry from the array items.
this seems to be some type of bug in what has focus?

![image](https://cloud.githubusercontent.com/assets/514002/4691074/a0cd3944-5704-11e4-953c-32cff0b414d6.png)
