### ISSUE TITLE
array of textAreas?

### ISSUE THREAD

**Issue by dcsan** [aldeed/meteor-autoform#448]
using nested types, its possible to have an array of one-line text Strings
but is there a way to have TextAreas work like this just with autoform?
or do i need to graduate to a custom form using af fields...?

example:

```
LocoBlob = new SimpleSchema
  en:
    label: "english"
    type: String
  ja:
    label: "japanese"
    type: String

# then reuse that in another schema
ExamplesSchema = new SimpleSchema
  text:
    type: LocoBlob
    optional: true

```

will give a nice nested object, but only one liner for each `String`:

![image](https://cloud.githubusercontent.com/assets/514002/4989258/9ac4a68a-692a-11e4-9f3f-e366e94cc0d6.png)

if I add autoform to the inner object like:

```
  en:
    label: "english"
    type: String
    autoform:
      type: 'textarea'
      rows: 5
```

I get a parse error 

and adding it to the outer object gives this:

![image](https://cloud.githubusercontent.com/assets/514002/4989248/77bbe8ce-692a-11e4-87ed-247afd752c4f.png)
