### ISSUE TITLE
valueOut and valueConverters are not called?

### ISSUE THREAD

**Issue by fusepilot** [aldeed/meteor-autoform#512]
I'm creating a custom input type for a price field. It needs to do 3 things. 

  1. Convert the value stored in the database as cents to dollars.
  2. Apply an currency input mask.
  3. Convert the inputed value back to cents for the datebase.

Here's my input type definition.

````
AutoForm.addInputType "cartPrice",
  template: "cartPrice"
  valueIn: (val) ->
    console.log "in", val
    val / 100
  valueOut: ->
    console.log "out", @val()
    @val() * 100
  valueConverters:
    string: (val) ->
      console.log "string convert", @val()
      val * 100
    number: (val) ->
      console.log "number convert", @val()
      val * 100

Template.cartPrice.rendered = ->
  $input = @$("input")
  $input.inputmask({ alias: "currency", prefix: "$"});
````

The template.

````
template(name="cartPrice")
  .input-price
    +afInputText_bootstrap3
````

And the schema.

````
ProductSchema = new SimpleSchema
  title:
    type: String
    optional: false

  price:
    type: Number
    label: "Price"
    min: 0
    decimal: false
    autoform:
      type: "cartPrice"
````

I've made a repo that demonstrates. https://github.com/fusepilot/autoform-valueOut-repro

1 and 2 work. But I can't get valueOut or valueConverters to ever be called. I only see valueIn's log in the console. Is this a bug or am I missing something?
