### ISSUE TITLE
Feature Request: common css-classes for children of Object-type

### ISSUE THREAD

**Issue by comerc** [aldeed/meteor-autoform#516]
```
Profiles.attachSchema new SimpleSchema
  basicInfo:
    type: Object
    autoform:
      "label-class": "col-sm-3"
      "input-col-class": "col-sm-9"
  "basicInfo.username":
    type: String
...
```

This feature allows us to abandon the assignment css-styles for each field in the template.
