### ISSUE TITLE
Feature for input type="date" - how to hide calendar-picker-indicator

### ISSUE THREAD

**Issue by comerc** [aldeed/meteor-autoform#611]
```css
::-webkit-calendar-picker-indicator { display: none; }
```

(i have some difficulties with `aldeed:autoform-bs-datepicker`, but input type="date" also have very strange calendar) 

I'm happy now
