### ISSUE TITLE
How to assign IDs to inputs?

### ISSUE THREAD

**Issue by ffxsam** [aldeed/meteor-autoform#957]
If I wanted to specify my own ID for an input field, how would I do that? I tried including `id` in the schema, but the page bombs out on me.

**Comment by sturoid** [comment]
Hi there. There are two ways (probably more) to do this:

1. Add it to the field in the schema:

```
Schema.Project = new SimpleSchema
   name:
      type: String
      autoform:
         id: 'someId'
```
or add it to the field directly:

```
+afQuickField(name='name' id='someId')
```
