### ISSUE TITLE
update-pushArray and custom autoForm template?

### ISSUE THREAD

**Issue by jgoley** [aldeed/meteor-autoform#962]
I'm having trouble using a custom template with the update-pushArray type.
I'm getting this error:
```Exception in template helper: Error: Invalid field name: stops at Object.getDefs```

Any ideas? Thanks!

(using jade templates)
```
+autoForm(
          collection="TourStops" 
          id="editTour"
          type="update-pushArray"
          doc=currentStops
          scope="stops"
          )
          +afArrayField name="stops" template="tap"
          input(type="submit")
```

**Schema (partial):**
```
TourStops.attachSchema new SimpleSchema
  'stops':
    type: Array
    optional: true
    minCount: 1
    maxCount: Infinity
    autoform:
      afFieldInput:
        options: () ->
          minCount: 1
  'stops.$':
    type: Object
    optional: true
```

**Custom Template:**
```
template(name="afArrayField_tap")
  {{ afFieldLabelText name=this.atts.name }}
  h1 stops
  +afEachArrayItem name="stops" minCount=1 maxCount=100
    +afQuickField name=this.current.title
    +afQuickField name=this.current.group

    if afFieldValueIs name=this.current.group value="single"
      +afQuickField name=this.current.speaker
      +afQuickField name=this.current.media
      +afQuickField name=this.current.type
    if afFieldValueIs name=this.current.group value="group"
      +afEachArrayItem name=this.current.childStops minCount=1 maxCount=10
        .autoform-array-item
          +afQuickField name=this.name label=false
          if afArrayFieldHasMoreThanMinimum name=this.arrayFieldName minCount=1 maxCount=10
            button.autoform-remove-item(type='button') Remove
                    
        if afArrayFieldHasLessThanMaximum name=this.name minCount=0 maxCount=10
          div(style='margin-top: 20px;')
            button.autoform-add-item(type='button', data-autoform-field='{{this.arrayFieldName}}', data-autoform-mincount='{{this.minCount}}', data-autoform-maxcount='{{this.maxCount}}') Add

    if afArrayFieldHasMoreThanMinimum name=../atts.name minCount=1 maxCount=10
        button.autoform-remove-item(type='button') Remove

  if afArrayFieldHasLessThanMaximum name=this.atts.name minCount=1 maxCount=10
    button.autoform-add-item(type='button', data-autoform-field='{{this.atts.name}}', data-autoform-mincount='{{this.atts.minCount}}', data-autoform-maxcount='{{this.atts.maxCount}}') Add
```
