### ISSUE TITLE
aFieldValueIs only fires once with inline radio buttons

### ISSUE THREAD

**Issue by sturoid** [aldeed/meteor-autoform#983]
With 5.3.0 the problem was fixed with aFieldValueIs and checkboxes, but now I can't seem to get radios to fire more than once. This is what I have:

```
repeatEnds:
   type: String
   optional: true
   autoform:
      type: 'select-radio-inline'
      options: -> [{ label: 'Never', value: 'never' },{ label: 'After', value: 'after' }, { label: 'On', value: 'on' }]
```

```    
.row
   .col-md-4
      +afQuickField(name='repeatEnds')
   .col-md-8
      if afFieldValueIs name='repeatEnds' value='after'
         +afQuickField(name='repeatEndsAfter')
      if afFieldValueIs name='repeatEnds' value='on'
         +afQuickField(name='repeatEndsOn')
```

If I click on the 'after' or 'on', I can't make anything else fire after that. Am I doing something wrong here or is this a problem?
